### ISSUE TITLE
If map named as just a number, map is produced, but stderr.txt for job shows a java.io.FileNotFoundException

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/GenePattern_NGCHM_BasicBuilder#5]
Create a map and put a single digit number for the map name.
I created one and used the number 5 and the following message was returned for stderr.txt
java.io.FileNotFoundException:  (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at mda.ngchm.datagenerator.MatrixValidator.validateClassificationFile(Unknown Source)
	at mda.ngchm.datagenerator.InputClass.<init>(Unknown Source)
	at mda.ngchm.datagenerator.ImportData.setHeatmapProperties(Unknown Source)
	at mda.ngchm.datagenerator.ImportData.<init>(Unknown Source)
	at mda.ngchm.datagenerator.HeatmapDataGenerator.processHeatMap(Unknown Source)
	at mda.ngchm.datagenerator.GalaxyMapGen.performMapGeneration(Unknown Source)
	at mda.ngchm.datagenerator.GalaxyMapGen.main(Unknown Source)
find: ‘./1583530025519/5’: No such file or directory

**Comment by jmelott** [comment]
Fix verified - 4/2/2020
